language: java
cache:
  directories:
  - $HOME/.gradle
script:
  - ./gradlew build --scan
deploy:
  provider: script
  script: ./gradlew bintrayUpload
  skip_cleanup: true
  on:
    branch: master
    tags: true
